### ISSUE TITLE
Mais coisas para a Economia

### ISSUE THREAD

**Issue by xGabrielDEV** [LunalaBot/Lunala#5]
A economia ainda faz poucas coisas, temos apenas o sistema de coins e um rascunho de comando de casino, sem contar com o comando $work que vai continuar do mesmo jeito.

Alguns comandos bons para a economia:
$rob, $fish, etc..

Poderiamos ter um sistema de comprar casas, carros e tals com o dinheiro.

Peço para que deixem sugestões para a economia nesse issue.

**Comment by JaosPiter** [comment]
Eu acho que deveria ter um sistema de lojinha, para comprar itens e ter algum uso, tipo um buff no trabalho

**Comment by xGabrielDEV** [comment]
> Eu acho que deveria ter um sistema de lojinha, para comprar itens e ter algum uso, tipo um buff no trabalho

Sim, uma boa ideia, talvez isso possa ser implementado.
